### ISSUE TITLE
marker可以支持自定义html或者jsx吗

### ISSUE THREAD

**Issue by conkyliu** [sxyhappy/react-maptalks#88]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/26617741/168015532-95ca385d-0c27-434d-8b92-f108a3d0bcd0.png">
<img width="386" alt="image" src="https://user-images.githubusercontent.com/26617741/168015617-770ae884-8a14-48f9-91f7-9170fe130ab2.png">
目前使用的是 [amap-react](https://jimnox.gitee.io/amap-react/docs/references/overlays/point/marker) 里面的Marker组件可以放jsx节点直接标记到地图。这个maptalks-react没有到可以支持html或者jsx的组件。请问要如何实现呢。

**Comment by sxyhappy** [comment]
库没写完 maptalks需要使用 uimarker https://maptalks.org/maptalks.js/api/1.x/ui.UIMarker.html 支持,传统的 marker 只支持 symbol https://github.com/maptalks/maptalks.js/wiki/Symbol-Reference

**Comment by conkyliu** [comment]
[amap-react](https://jimnox.gitee.io/amap-react/docs/references/overlays/point/marker)

> 

这个jsx组件可以转成html吗，用官方的UIMarker。

**Comment by conkyliu** [comment]
> 库没写完 maptalks需要使用 uimarker https://maptalks.org/maptalks.js/api/1.x/ui.UIMarker.html 支持,传统的 marker 只支持 symbol https://github.com/maptalks/maptalks.js/wiki/Symbol-Reference


这个jsx组件可以转成html吗，用官方的UIMarker。

**Comment by sxyhappy** [comment]
可以 uimarker content 支持 dom, 可以使用 reactDom.render 返回 dom 赋值给 content,但是好像 react 18, reactDom.render 被废弃了

**Comment by sxyhappy** [comment]
可以参照这个 https://github.com/sxyhappy/react-maptalks/blob/master/packages/react-maptalks/src/ui/MtInfoWindow.tsx

**Comment by conkyliu** [comment]
> 可以 uimarker content 支持 dom, 可以使用 reactDom.render 返回 dom 赋值给 content,但是好像 react 18, reactDom.render 被废弃了

好的，我尝试下，目前18太新了，谢谢。

**Comment by conkyliu** [comment]
是得集成进UIMarker才可以使用吗

**Comment by sxyhappy** [comment]
maptalks 直接有这个class 的 直接 new 就可以
