### ISSUE TITLE
请问如何获取Marker的点击click事件

### ISSUE THREAD

**Issue by conkyliu** [sxyhappy/react-maptalks#89]
使用这种方式生成marker， https://sxyhappy.github.io/react-maptalks/docs/components/layers/vector-layer

如何获取点击marker的点击事件呢
![截屏2022-05-16 17 05 40](https://user-images.githubusercontent.com/26617741/168558074-b001fc8d-ea67-45a8-9b88-4ad1ece20e26.png)

**Comment by sxyhappy** [comment]
直接const marker = new maptalks.marker 需要在 marker 上监听事件
marker.on(‘click’, () => {})

**Comment by conkyliu** [comment]
> 直接const marker = new maptalks.marker 需要在 marker 上监听事件
> marker.on(‘click’, () => {})

好的，谢谢！
